$missingFiles = @(
    "arcface_converter_ghost.onnx",
    "arcface_converter_hififace.hash",
    "arcface_converter_hififace.onnx",
    "arcface_converter_simswap.hash",
    "arcface_converter_simswap.onnx",
    "bisenet_resnet_18.hash",
    "bisenet_resnet_18.onnx",
    "bisenet_resnet_34.hash",
    "bisenet_resnet_34.onnx",
    "clear_reality_x4.onnx",
    "ddcolor.onnx",
    "ddcolor_artistic.onnx",
    "deoldify.onnx",
    "deoldify_artistic.hash",
    "deoldify_artistic.onnx",
    "deoldify_stable.hash",
    "deoldify_stable.onnx",
    "fairface.hash",
    "fairface.onnx",
    "gfpgan_1.4.hash",
    "gfpgan_1.4.onnx",
    "ghost_1_256.onnx",
    "ghost_2_256.hash",
    "ghost_2_256.onnx",
    "ghost_3_256.hash",
    "ghost_3_256.onnx",
    "gpen_bfr_1024.hash",
    "gpen_bfr_1024.onnx",
    "gpen_bfr_2048.hash",
    "gpen_bfr_2048.onnx",
    "gpen_bfr_256.hash",
    "gpen_bfr_256.onnx",
    "gpen_bfr_512.hash",
    "gpen_bfr_512.onnx",
    "hififace_unofficial_256.hash",
    "hififace_unofficial_256.onnx",
    "hyperswap_1a_256.hash",
    "hyperswap_1a_256.onnx",
    "hyperswap_1b_256.hash",
    "hyperswap_1b_256.onnx",
    "hyperswap_1c_256.hash",
    "hyperswap_1c_256.onnx",
    "inswapper_128.hash",
    "inswapper_128.onnx",
    "live_portrait_eye_retargeter.onnx",
    "live_portrait_feature_extractor.onnx",
    "live_portrait_generator.onnx",
    "live_portrait_lip_retargeter.onnx",
    "live_portrait_motion_extractor.onnx",
    "live_portrait_stitcher.onnx",
    "lsdir_x4.onnx",
    "nomos8k_sc_x4.onnx",
    "real_esrgan_x2.hash",
    "real_esrgan_x2.onnx",
    "real_esrgan_x2_fp16.hash",
    "real_esrgan_x2_fp16.onnx",
    "real_esrgan_x4.hash",
    "real_esrgan_x4.onnx",
    "real_esrgan_x4_fp16.hash",
    "real_esrgan_x4_fp16.onnx",
    "real_esrgan_x8.hash",
    "real_esrgan_x8.onnx",
    "real_esrgan_x8_fp16.hash",
    "real_esrgan_x8_fp16.onnx",
    "real_hatgan_x4.hash",
    "real_hatgan_x4.onnx",
    "real_web_photo_x4.hash",
    "real_web_photo_x4.onnx",
    "realistic_rescaler_x4.hash",
    "realistic_rescaler_x4.onnx",
    "remacri_x4.hash",
    "remacri_x4.onnx",
    "restoreformer_plus_plus.hash",
    "restoreformer_plus_plus.onnx",
    "siax_x4.hash",
    "siax_x4.onnx",
    "simswap_256.hash",
    "simswap_256.onnx",
    "simswap_unofficial_512.hash",
    "simswap_unofficial_512.onnx",
    "span_kendata_x4.hash",
    "span_kendata_x4.onnx",
    "styleganex_age.hash",
    "styleganex_age.onnx",
    "swin2_sr_x4.hash",
    "swin2_sr_x4.onnx",
    "ultra_sharp_2_x4.hash",
    "ultra_sharp_2_x4.onnx",
    "ultra_sharp_x4.hash",
    "ultra_sharp_x4.onnx",
    "uniface_256.hash",
    "uniface_256.onnx",
    "wav2lip_96.onnx",
    "wav2lip_gan_96.onnx",
    "xseg_3.hash",
    "xseg_3.onnx"
)
$targetDir = "facefusion/.assets/models"
if (!(Test-Path $targetDir)) { New-Item -ItemType Directory -Path $targetDir -Force }
foreach ($file in $missingFiles) {
    $url = "https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/$file"
    Write-Host "Downloading $file ..."
    try {
        Invoke-WebRequest -Uri $url -OutFile "$targetDir/$file" -ErrorAction Stop
    } catch {
        Write-Host "Failed to download $file from $url"
    }
}
Write-Host "All missing model files download attempted." 